//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSOCIADOSPROMOCOES
    {
        public int IdAssociadoPromocao { get; set; }
        public int IdEmpresa { get; set; }
        public int IdAssociado { get; set; }
        public int IdPeriodo { get; set; }
        public int IdCargoAnterior { get; set; }
        public int IdCargoAtual { get; set; }
        public string Comentarios { get; set; }
        public int USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual CARGOS CARGOS { get; set; }
        public virtual CARGOS CARGOS1 { get; set; }
        public virtual PERIODOSAVALIACOES PERIODOSAVALIACOES { get; set; }
    }
}
