//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSOCIADOSTEMP
    {
        public int IdAssociado { get; set; }
        public int IdEmpresa { get; set; }
        public int IdAssociadoMentor { get; set; }
        public int IdCargo { get; set; }
        public int IdPerfil { get; set; }
        public int IdNivel { get; set; }
        public int IdStatus { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public int USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
    }
}
