//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSOCIADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSOCIADOS()
        {
            this.ASSOCIADOS1 = new HashSet<ASSOCIADOS>();
            this.ASSOCIADOS11 = new HashSet<ASSOCIADOS>();
            this.ASSOCIADOSPROMOCOES = new HashSet<ASSOCIADOSPROMOCOES>();
            this.AVALIACAO = new HashSet<AVALIACAO>();
            this.AVALIACAO1 = new HashSet<AVALIACAO>();
            this.AVALIACOESCOMPETENCIAS = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS1 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS2 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS3 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS4 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS5 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS6 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESPERFORMANCES = new HashSet<AVALIACOESPERFORMANCES>();
            this.AVALIACOESPERFORMANCES1 = new HashSet<AVALIACOESPERFORMANCES>();
            this.AVALIACOESPERFORMANCES2 = new HashSet<AVALIACOESPERFORMANCES>();
            this.AVALIACOESPERFORMANCES3 = new HashSet<AVALIACOESPERFORMANCES>();
            this.AVALIACOESPERFORMANCES4 = new HashSet<AVALIACOESPERFORMANCES>();
            this.AVALIACOESPERFORMANCES5 = new HashSet<AVALIACOESPERFORMANCES>();
            this.AVALIACOESPERFORMANCES6 = new HashSet<AVALIACOESPERFORMANCES>();
            this.CLIENTES = new HashSet<CLIENTES>();
            this.COMPETENCIAS = new HashSet<COMPETENCIAS>();
            this.DIMENSOES = new HashSet<DIMENSOES>();
            this.EIXOS = new HashSet<EIXOS>();
            this.PERFORMANCES = new HashSet<PERFORMANCES>();
            this.PROJETOS = new HashSet<PROJETOS>();
            this.PROJETOS1 = new HashSet<PROJETOS>();
            this.PROJETOS2 = new HashSet<PROJETOS>();
            this.PROJETOSASSOCIADOS = new HashSet<PROJETOSASSOCIADOS>();
            this.PROJETOSASSOCIADOS1 = new HashSet<PROJETOSASSOCIADOS>();
            this.PROJETOSASSOCIADOS2 = new HashSet<PROJETOSASSOCIADOS>();
            this.PROJETOSASSOCIADOS3 = new HashSet<PROJETOSASSOCIADOS>();
            this.SUBCOMPETENCIAS = new HashSet<SUBCOMPETENCIAS>();
            this.WORKFLOW = new HashSet<WORKFLOW>();
            this.EVOLUCAOASSOCIADO = new HashSet<EVOLUCAOASSOCIADO>();
            this.CONSIDERACOESMENTOR = new HashSet<CONSIDERACOESMENTOR>();
            this.CONSIDERACOESMENTOR1 = new HashSet<CONSIDERACOESMENTOR>();
            this.EQUIPE = new HashSet<EQUIPE>();
            this.EQUIPE1 = new HashSet<EQUIPE>();
            this.PROMOCOES = new HashSet<PROMOCOES>();
            this.PRAZOS = new HashSet<PRAZOS>();
            this.LIDERESFRENTEINTERNA = new HashSet<LIDERESFRENTEINTERNA>();
            this.PARTICIPANTESFRENTEINTERNA = new HashSet<PARTICIPANTESFRENTEINTERNA>();
            this.PDI_RESPOSTAS = new HashSet<PDI_RESPOSTAS>();
            this.COMENTARIOS = new HashSet<COMENTARIOS>();
            this.AVALIACOESALOCACOESINTERNAS = new HashSet<AVALIACOESALOCACOESINTERNAS>();
            this.AVALIACOESALOCACOESINTERNAS1 = new HashSet<AVALIACOESALOCACOESINTERNAS>();
            this.MENTORADORESPOSTAS = new HashSet<MENTORADORESPOSTAS>();
            this.MENTORADORESPOSTAS1 = new HashSet<MENTORADORESPOSTAS>();
            this.FOTOSASSOCIADOS = new HashSet<FOTOSASSOCIADOS>();
        }
    
        public int IdAssociado { get; set; }
        public int IdEmpresa { get; set; }
        public int IdAssociadoMentor { get; set; }
        public int IdCargo { get; set; }
        public int IdPerfil { get; set; }
        public int IdNivel { get; set; }
        public int IdStatus { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public int USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public string FotoNome { get; set; }
        public Nullable<System.DateTime> DataAdmissao { get; set; }
        public string Vertical { get; set; }
        public Nullable<int> IdVertical { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSOCIADOS> ASSOCIADOS1 { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSOCIADOS> ASSOCIADOS11 { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS3 { get; set; }
        public virtual CARGOS CARGOS { get; set; }
        public virtual EMPRESAS EMPRESAS { get; set; }
        public virtual CARGOSNIVEIS CARGOSNIVEIS { get; set; }
        public virtual PERFIS PERFIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSOCIADOSPROMOCOES> ASSOCIADOSPROMOCOES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACAO> AVALIACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACAO> AVALIACAO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTES> CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPETENCIAS> COMPETENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIMENSOES> DIMENSOES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EIXOS> EIXOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFORMANCES> PERFORMANCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJETOS> PROJETOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJETOS> PROJETOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJETOS> PROJETOS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJETOSASSOCIADOS> PROJETOSASSOCIADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJETOSASSOCIADOS> PROJETOSASSOCIADOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJETOSASSOCIADOS> PROJETOSASSOCIADOS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJETOSASSOCIADOS> PROJETOSASSOCIADOS3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBCOMPETENCIAS> SUBCOMPETENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKFLOW> WORKFLOW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVOLUCAOASSOCIADO> EVOLUCAOASSOCIADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIDERACOESMENTOR> CONSIDERACOESMENTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIDERACOESMENTOR> CONSIDERACOESMENTOR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPE> EQUIPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPE> EQUIPE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROMOCOES> PROMOCOES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRAZOS> PRAZOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIDERESFRENTEINTERNA> LIDERESFRENTEINTERNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTICIPANTESFRENTEINTERNA> PARTICIPANTESFRENTEINTERNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDI_RESPOSTAS> PDI_RESPOSTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMENTARIOS> COMENTARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESALOCACOESINTERNAS> AVALIACOESALOCACOESINTERNAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESALOCACOESINTERNAS> AVALIACOESALOCACOESINTERNAS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENTORADORESPOSTAS> MENTORADORESPOSTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENTORADORESPOSTAS> MENTORADORESPOSTAS1 { get; set; }
        public virtual VERTICAL VERTICAL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOTOSASSOCIADOS> FOTOSASSOCIADOS { get; set; }
    }
}
