//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVALIACAO
    {
        public int idAvaliacao { get; set; }
        public int idEmpresa { get; set; }
        public int idProjeto { get; set; }
        public int idAssociado { get; set; }
        public int idPeriodo { get; set; }
        public int idStatus { get; set; }
        public bool Liberado { get; set; }
        public Nullable<System.DateTime> DataLiberacao { get; set; }
        public string PosicaoAtualFluxoAvaliacao { get; set; }
        public int USR { get; set; }
        public System.DateTime DHC { get; set; }
        public string TipoAvaliacao { get; set; }
        public string Escopo { get; set; }
        public Nullable<int> idGestor { get; set; }
        public int IdPrazo { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS1 { get; set; }
        public virtual AVALIACOESSTATUS AVALIACOESSTATUS { get; set; }
        public virtual EMPRESAS EMPRESAS { get; set; }
        public virtual PERIODOSAVALIACOES PERIODOSAVALIACOES { get; set; }
        public virtual PROJETOS PROJETOS { get; set; }
        public virtual PRAZOS PRAZOS { get; set; }
    }
}
