//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVALIACOESCOMPETENCIAS_HISTORICO
    {
        public int IdAvaliacaoCompetenciaHistorico { get; set; }
        public int IdAvaliacaoCompetencia { get; set; }
        public int IdEmpresa { get; set; }
        public int IdAssociado { get; set; }
        public string Associado { get; set; }
        public int IdCargo { get; set; }
        public string Cargo { get; set; }
        public int IdNivel { get; set; }
        public string Nivel { get; set; }
        public int IdProjeto { get; set; }
        public string Projeto { get; set; }
        public int IdPeriodo { get; set; }
        public string Periodo { get; set; }
        public int IdCompetencia { get; set; }
        public string Competencia { get; set; }
        public int IdEixo { get; set; }
        public string Eixo { get; set; }
        public int IdSubCompetencia { get; set; }
        public string SubCompetencia { get; set; }
        public int IdDimensao { get; set; }
        public string Dimensao { get; set; }
        public int IdAvaliacaoStatus { get; set; }
        public string AvaliacaoStatus { get; set; }
        public System.DateTime DataHoraInicio { get; set; }
        public Nullable<System.DateTime> DataHoraTermino { get; set; }
        public string PosicaoAtualFluxoAvaliacao { get; set; }
        public int IdNotaNivel1AutoAvaliacao { get; set; }
        public string NotaNivel1AutoAvaliacao { get; set; }
        public int IdNotaNivel2AutoAvaliacao { get; set; }
        public string NotaNivel2AutoAvaliacao { get; set; }
        public string ComentariosAutoAvaliacao { get; set; }
        public System.DateTime DHCAutoAvaliacao { get; set; }
        public int USRAutoAvaliacao { get; set; }
        public Nullable<int> IdNotaNivel1AvaliacaoCegas { get; set; }
        public string NotaNivel1AvaliacaoCegas { get; set; }
        public Nullable<int> IdNotaNivel2AvaliacaoCegas { get; set; }
        public string NotaNivel2AvaliacaoCegas { get; set; }
        public string ComentariosAvaliacaoCegas { get; set; }
        public Nullable<System.DateTime> DHCAvaliacaoCegas { get; set; }
        public Nullable<int> USRAvaliacaoCegas { get; set; }
        public Nullable<int> IdNotaNivel1AvaliacaoGestor { get; set; }
        public string Notanivel1AvaliacaoGestor { get; set; }
        public Nullable<int> IdNotaNivel2AvaliacaoGestor { get; set; }
        public string NotaNivel2AvaliacaoGestor { get; set; }
        public string ComentariosAvaliacaoGestor { get; set; }
        public Nullable<System.DateTime> DHCAvaliacaoGestor { get; set; }
        public Nullable<int> USRAvaliacaoGestor { get; set; }
        public Nullable<int> IdNotaNivel1Feedback { get; set; }
        public string NotaNivel1Feedback { get; set; }
        public Nullable<int> IdNotaNivel2Feedback { get; set; }
        public string NotaNivel2Feedback { get; set; }
        public string ComentariosFeedback { get; set; }
        public Nullable<System.DateTime> DHCFeedback { get; set; }
        public Nullable<int> USRFeedback { get; set; }
        public Nullable<int> IdNotaNivel1AvaliacaoMentor { get; set; }
        public string NotaNivel1AvaliacaoMentor { get; set; }
        public Nullable<int> IdNotaNivel2AvaliacaoMentor { get; set; }
        public string NotaNivel2AvaliacaoMentor { get; set; }
        public string ComentariosAvaliacaoMentor { get; set; }
        public Nullable<System.DateTime> DHCAvaliacaoMentor { get; set; }
        public Nullable<int> USRAvaliacaoMentor { get; set; }
        public Nullable<int> Notificado { get; set; }
        public Nullable<System.DateTime> DataHoraNotificacao { get; set; }
        public int USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public Nullable<System.DateTime> DataHoraiNICIOAutoAvaliacao { get; set; }
        public Nullable<System.DateTime> DataHoraFimAutoAvaliacao { get; set; }
        public Nullable<System.DateTime> DataHoraInicioAvaliacaoCegas { get; set; }
        public Nullable<System.DateTime> DataHoraFimAvaliacaoCegas { get; set; }
        public Nullable<System.DateTime> DataHoraInicioAvaliacaoGestor { get; set; }
        public Nullable<System.DateTime> DataHoraFimAvaliacaoGestor { get; set; }
        public Nullable<System.DateTime> DataHoraInicioFeedback { get; set; }
        public Nullable<System.DateTime> DataHoraFimFeedback { get; set; }
        public Nullable<System.DateTime> DataHoraInicioAvaliacaoMentor { get; set; }
        public Nullable<System.DateTime> DataHoraFimAvaliacaoMentor { get; set; }
    
        public virtual AVALIACOESCOMPETENCIAS AVALIACOESCOMPETENCIAS { get; set; }
    }
}
