//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVALIACOESCOMPETENCIAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AVALIACOESCOMPETENCIAS()
        {
            this.AVALIACOESCOMPETENCIAS_HISTORICO = new HashSet<AVALIACOESCOMPETENCIAS_HISTORICO>();
        }
    
        public int IdAvaliacaoCompetencia { get; set; }
        public int IdEmpresa { get; set; }
        public int IdAssociado { get; set; }
        public int IdCargo { get; set; }
        public int IdNivel { get; set; }
        public int IdProjeto { get; set; }
        public int IdPeriodo { get; set; }
        public int IdCompetencia { get; set; }
        public int IdAvaliacaoStatus { get; set; }
        public System.DateTime DataHoraInicio { get; set; }
        public Nullable<System.DateTime> DataHoraTermino { get; set; }
        public string PosicaoAtualFluxoAvaliacao { get; set; }
        public int IdNotaNivel1AutoAvaliacao { get; set; }
        public int IdNotaNivel2AutoAvaliacao { get; set; }
        public string ComentariosAutoAvaliacao { get; set; }
        public System.DateTime DHCAutoAvaliacao { get; set; }
        public int USRAutoAvaliacao { get; set; }
        public Nullable<int> IdNotaNivel1AvaliacaoCegas { get; set; }
        public Nullable<int> IdNotaNivel2AvaliacaoCegas { get; set; }
        public string ComentariosAvaliacaoCegas { get; set; }
        public Nullable<System.DateTime> DHCAvaliacaoCegas { get; set; }
        public Nullable<int> USRAvaliacaoCegas { get; set; }
        public Nullable<int> IdNotaNivel1AvaliacaoGestor { get; set; }
        public Nullable<int> IdNotaNivel2AvaliacaoGestor { get; set; }
        public string ComentariosAvaliacaoGestor { get; set; }
        public Nullable<System.DateTime> DHCAvaliacaoGestor { get; set; }
        public Nullable<int> USRAvaliacaoGestor { get; set; }
        public Nullable<int> IdNotaNivel1Feedback { get; set; }
        public Nullable<int> IdNotaNivel2Feedback { get; set; }
        public string ComentariosFeedback { get; set; }
        public Nullable<System.DateTime> DHCFeedback { get; set; }
        public Nullable<int> USRFeedback { get; set; }
        public Nullable<int> IdNotaNivel1AvaliacaoMentor { get; set; }
        public Nullable<int> IdNotaNivel2AvaliacaoMentor { get; set; }
        public string ComentariosAvaliacaoMentor { get; set; }
        public Nullable<System.DateTime> DHCAvaliacaoMentor { get; set; }
        public Nullable<int> USRAvaliacaoMentor { get; set; }
        public Nullable<int> Notificado { get; set; }
        public Nullable<System.DateTime> DataHoraNotificacao { get; set; }
        public int USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public Nullable<System.DateTime> DataHoraInicioAutoAvaliacao { get; set; }
        public Nullable<System.DateTime> DataHoraFimAutoAvaliacao { get; set; }
        public Nullable<System.DateTime> DataHoraInicioAvaliacaoCegas { get; set; }
        public Nullable<System.DateTime> DataHoraFimAvaliacaoCegas { get; set; }
        public Nullable<System.DateTime> DataHoraInicioAvaliacaoGestor { get; set; }
        public Nullable<System.DateTime> DataHoraFimAvaliacaoGestor { get; set; }
        public Nullable<System.DateTime> DataHoraInicioFeedback { get; set; }
        public Nullable<System.DateTime> DataHoraFimFeedback { get; set; }
        public Nullable<System.DateTime> DataHoraInicioAvaliacaoMentor { get; set; }
        public Nullable<System.DateTime> DataHoraFimAvaliacaoMentor { get; set; }
        public Nullable<int> IdAvaliacaoPerformance { get; set; }
        public Nullable<decimal> NotaSubCompetenciaAvaliado { get; set; }
        public Nullable<decimal> NotaSubCompetenciaGestor { get; set; }
        public Nullable<decimal> NotaCompetenciaAvaliado { get; set; }
        public Nullable<decimal> NotaCompetenciaGestor { get; set; }
        public Nullable<decimal> NotaFinalNivel1 { get; set; }
        public Nullable<decimal> NotaFinalNivel2 { get; set; }
        public Nullable<int> IdNotaNivel1Comite { get; set; }
        public Nullable<int> IdNotaNivel2Comite { get; set; }
        public string TipoAvaliacao { get; set; }
        public string Escopo { get; set; }
        public int idAvaliacao { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS1 { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS2 { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS3 { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS4 { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS5 { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS6 { get; set; }
        public virtual AVALIACOESCOMPETENCIASNOTAS AVALIACOESCOMPETENCIASNOTAS { get; set; }
        public virtual AVALIACOESCOMPETENCIASNOTAS AVALIACOESCOMPETENCIASNOTAS1 { get; set; }
        public virtual AVALIACOESCOMPETENCIASNOTAS AVALIACOESCOMPETENCIASNOTAS2 { get; set; }
        public virtual AVALIACOESCOMPETENCIASNOTAS AVALIACOESCOMPETENCIASNOTAS3 { get; set; }
        public virtual AVALIACOESCOMPETENCIASNOTAS AVALIACOESCOMPETENCIASNOTAS4 { get; set; }
        public virtual AVALIACOESCOMPETENCIASNOTAS AVALIACOESCOMPETENCIASNOTAS5 { get; set; }
        public virtual AVALIACOESCOMPETENCIASNOTAS AVALIACOESCOMPETENCIASNOTAS6 { get; set; }
        public virtual AVALIACOESCOMPETENCIASNOTAS AVALIACOESCOMPETENCIASNOTAS7 { get; set; }
        public virtual AVALIACOESCOMPETENCIASNOTAS AVALIACOESCOMPETENCIASNOTAS8 { get; set; }
        public virtual AVALIACOESCOMPETENCIASNOTAS AVALIACOESCOMPETENCIASNOTAS9 { get; set; }
        public virtual AVALIACOESPERFORMANCES AVALIACOESPERFORMANCES { get; set; }
        public virtual AVALIACOESSTATUS AVALIACOESSTATUS { get; set; }
        public virtual CARGOS CARGOS { get; set; }
        public virtual CARGOS CARGOS1 { get; set; }
        public virtual CARGOSNIVEIS CARGOSNIVEIS { get; set; }
        public virtual COMPETENCIAS COMPETENCIAS { get; set; }
        public virtual EMPRESAS EMPRESAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS_HISTORICO> AVALIACOESCOMPETENCIAS_HISTORICO { get; set; }
        public virtual PERIODOSAVALIACOES PERIODOSAVALIACOES { get; set; }
        public virtual PROJETOS PROJETOS { get; set; }
        public virtual AVALIACOESCOMPETENCIASNOTAS AVALIACOESCOMPETENCIASNOTAS10 { get; set; }
        public virtual AVALIACOESCOMPETENCIASNOTAS AVALIACOESCOMPETENCIASNOTAS11 { get; set; }
    }
}
