//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVALIACOESPERFORMANCESNOTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AVALIACOESPERFORMANCESNOTAS()
        {
            this.AVALIACOESPERFORMANCES = new HashSet<AVALIACOESPERFORMANCES>();
            this.AVALIACOESPERFORMANCES1 = new HashSet<AVALIACOESPERFORMANCES>();
            this.AVALIACOESPERFORMANCES2 = new HashSet<AVALIACOESPERFORMANCES>();
            this.AVALIACOESPERFORMANCES3 = new HashSet<AVALIACOESPERFORMANCES>();
            this.AVALIACOESPERFORMANCES4 = new HashSet<AVALIACOESPERFORMANCES>();
            this.AVALIACOESPERFORMANCES5 = new HashSet<AVALIACOESPERFORMANCES>();
        }
    
        public int IdNota { get; set; }
        public string CodigoNota { get; set; }
        public string DescricaoNota { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public Nullable<bool> IndFeedback { get; set; }
        public Nullable<decimal> Peso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES5 { get; set; }
    }
}
