//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVALIACOESCOMPETENCIASNOTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AVALIACOESCOMPETENCIASNOTAS()
        {
            this.AVALIACOESCOMPETENCIAS = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS1 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS2 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS3 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS4 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS5 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS6 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS7 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS8 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS9 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS10 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS11 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.COMPETENCIAS = new HashSet<COMPETENCIAS>();
            this.COMPETENCIAS1 = new HashSet<COMPETENCIAS>();
        }
    
        public int IdNota { get; set; }
        public string CodigoNota { get; set; }
        public string DescricaoNota { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public string CodigoNotaAvaliador { get; set; }
        public Nullable<bool> IndFeedback { get; set; }
        public Nullable<decimal> Peso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPETENCIAS> COMPETENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPETENCIAS> COMPETENCIAS1 { get; set; }
    }
}
