//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVALIACOESALOCACOESINTERNAS
    {
        public int idAvaliacaoAlocacaoInterna { get; set; }
        public int idAvaliador { get; set; }
        public int idAssociado { get; set; }
        public int idPeriodo { get; set; }
        public int idNota { get; set; }
        public string Comentarios { get; set; }
        public System.DateTime DHC { get; set; }
        public int idAlocacaoInterna { get; set; }
        public Nullable<bool> ValidadoMD { get; set; }
        public Nullable<System.DateTime> DHCValidadoMD { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS1 { get; set; }
        public virtual NOTASALOCACOESINTERNAS NOTASALOCACOESINTERNAS { get; set; }
        public virtual PERIODOSAVALIACOES PERIODOSAVALIACOES { get; set; }
        public virtual FRENTEINTERNA FRENTEINTERNA { get; set; }
    }
}
