//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARGOS()
        {
            this.ASSOCIADOS = new HashSet<ASSOCIADOS>();
            this.ASSOCIADOSPROMOCOES = new HashSet<ASSOCIADOSPROMOCOES>();
            this.ASSOCIADOSPROMOCOES1 = new HashSet<ASSOCIADOSPROMOCOES>();
            this.AVALIACOESCOMPETENCIAS = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESCOMPETENCIAS1 = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESPERFORMANCES = new HashSet<AVALIACOESPERFORMANCES>();
            this.CARGOS1 = new HashSet<CARGOS>();
            this.COMPETENCIAS = new HashSet<COMPETENCIAS>();
            this.PERFORMANCES = new HashSet<PERFORMANCES>();
            this.PREMISSAS_RADAR = new HashSet<PREMISSAS_RADAR>();
            this.PROMOCOES = new HashSet<PROMOCOES>();
            this.PROMOCOES1 = new HashSet<PROMOCOES>();
            this.RELACAO_CARGO_SUBCOMPETENCIA = new HashSet<RELACAO_CARGO_SUBCOMPETENCIA>();
        }
    
        public int IdCargo { get; set; }
        public string Cargo { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public Nullable<int> idProximoCargo { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public string RegimeContratacao { get; set; }
        public int TempoMinimoPromocao { get; set; }
        public string Funcao { get; set; }
        public string Autonomia { get; set; }
        public string EscopoDeAtuacao { get; set; }
        public string NivelInterlocucao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSOCIADOS> ASSOCIADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSOCIADOSPROMOCOES> ASSOCIADOSPROMOCOES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSOCIADOSPROMOCOES> ASSOCIADOSPROMOCOES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARGOS> CARGOS1 { get; set; }
        public virtual CARGOS CARGOS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPETENCIAS> COMPETENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFORMANCES> PERFORMANCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREMISSAS_RADAR> PREMISSAS_RADAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROMOCOES> PROMOCOES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROMOCOES> PROMOCOES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELACAO_CARGO_SUBCOMPETENCIA> RELACAO_CARGO_SUBCOMPETENCIA { get; set; }
    }
}
