//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGOSNIVEIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARGOSNIVEIS()
        {
            this.ASSOCIADOS = new HashSet<ASSOCIADOS>();
            this.AVALIACOESCOMPETENCIAS = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESPERFORMANCES = new HashSet<AVALIACOESPERFORMANCES>();
            this.COMPETENCIAS = new HashSet<COMPETENCIAS>();
            this.PERFORMANCES = new HashSet<PERFORMANCES>();
            this.PREMISSAS_RADAR = new HashSet<PREMISSAS_RADAR>();
        }
    
        public int IdNivel { get; set; }
        public string Nivel { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSOCIADOS> ASSOCIADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPETENCIAS> COMPETENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFORMANCES> PERFORMANCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREMISSAS_RADAR> PREMISSAS_RADAR { get; set; }
    }
}
