//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTES()
        {
            this.PROJETOS = new HashSet<PROJETOS>();
        }
    
        public int IdCliente { get; set; }
        public int IdEmpresa { get; set; }
        public int IdAssociacoResponsavel { get; set; }
        public int IdAssociadoGestor { get; set; }
        public string Cliente { get; set; }
        public string Email { get; set; }
        public string Telefones { get; set; }
        public int USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public string GestorCliente { get; set; }
        public string CODIGO { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual EMPRESAS EMPRESAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJETOS> PROJETOS { get; set; }
    }
}
