//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPETENCIAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPETENCIAS()
        {
            this.AVALIACOESCOMPETENCIAS = new HashSet<AVALIACOESCOMPETENCIAS>();
        }
    
        public int IdCompetencia { get; set; }
        public int IdEmpresa { get; set; }
        public int IdCargo { get; set; }
        public int IdNivel { get; set; }
        public int IdEixo { get; set; }
        public int IdSubCompetencia { get; set; }
        public int IdDimensao { get; set; }
        public string CompetenciaJRDetalhe { get; set; }
        public string CompetenciaJR { get; set; }
        public string CompetenciaPLDetalhe { get; set; }
        public string CompetenciaPL { get; set; }
        public string CompetenciaSRDetalhe { get; set; }
        public string CompetenciaSR { get; set; }
        public int USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public string TipoAvaliacao { get; set; }
        public string Escopo { get; set; }
        public string PalavrasChave { get; set; }
        public bool InputAutoAvaliacao { get; set; }
        public bool InputAvaliacaoAsCegas { get; set; }
        public bool InputAvaliacaoGestor { get; set; }
        public bool InputFeedback { get; set; }
        public bool InputNivel1 { get; set; }
        public bool InputNivel2 { get; set; }
        public bool VisivelAutoAvaliacao { get; set; }
        public bool VisivelAvaliacaoAsCegas { get; set; }
        public bool VisivelAvaliacaoGestor { get; set; }
        public bool VisivelFeedback { get; set; }
        public bool VisivelNivel1 { get; set; }
        public bool VisivelNivel2 { get; set; }
        public Nullable<int> IdNotaPadraoNivel1 { get; set; }
        public Nullable<int> IdNotaPadraoNivel2 { get; set; }
        public Nullable<int> IdReferenciaPerformance { get; set; }
        public int IdModo { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS { get; set; }
        public virtual CARGOS CARGOS { get; set; }
        public virtual CARGOSNIVEIS CARGOSNIVEIS { get; set; }
        public virtual DIMENSOES DIMENSOES { get; set; }
        public virtual EIXOS EIXOS { get; set; }
        public virtual EMPRESAS EMPRESAS { get; set; }
        public virtual SUBCOMPETENCIAS SUBCOMPETENCIAS { get; set; }
        public virtual AVALIACOESCOMPETENCIASNOTAS AVALIACOESCOMPETENCIASNOTAS { get; set; }
        public virtual AVALIACOESCOMPETENCIASNOTAS AVALIACOESCOMPETENCIASNOTAS1 { get; set; }
        public virtual MODOCALCULOCOMPETENCIAS MODOCALCULOCOMPETENCIAS { get; set; }
    }
}
