//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPLEXIDADE
    {
        public int IdComplexidade { get; set; }
        public string Complexidade1 { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public decimal Ponderacao { get; set; }
        public decimal FaixaPonderacaoInicial { get; set; }
        public decimal FaixaPonderacaoFinal { get; set; }
    }
}
