//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSIDERACOESMENTOR
    {
        public int idConsideracoesMentor { get; set; }
        public int idMentor { get; set; }
        public int idAssociado { get; set; }
        public int idPeriodo { get; set; }
        public string TipoAvaliacao { get; set; }
        public string Escopo { get; set; }
        public bool ElegivelPromocao { get; set; }
        public bool InputPromocao { get; set; }
        public string TrajetoriaAssociado { get; set; }
        public string PontosFortes { get; set; }
        public string PontosFracos { get; set; }
        public Nullable<bool> LiberadoRH { get; set; }
        public string AcaoComite { get; set; }
        public string PontosFortesRH { get; set; }
        public string PontosFracosRH { get; set; }
        public Nullable<decimal> SalarioAtual { get; set; }
        public Nullable<decimal> SalarioNovo { get; set; }
        public string RegimeContratacaoAtual { get; set; }
        public string RegimeContratacaoNovo { get; set; }
        public bool MentoriaRealizada { get; set; }
        public Nullable<System.DateTime> DataLiberadoRH { get; set; }
        public Nullable<System.DateTime> DataMentoriaRealizada { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS1 { get; set; }
        public virtual PERIODOSAVALIACOES PERIODOSAVALIACOES { get; set; }
    }
}
