//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataModel : DbContext
    {
        public DataModel()
            : base("name=DataModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AVALIACOESSTATUS> AVALIACOESSTATUS { get; set; }
        public virtual DbSet<ASSOCIADOS> ASSOCIADOS { get; set; }
        public virtual DbSet<ASSOCIADOSPROMOCOES> ASSOCIADOSPROMOCOES { get; set; }
        public virtual DbSet<AVALIACAO> AVALIACAO { get; set; }
        public virtual DbSet<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS { get; set; }
        public virtual DbSet<AVALIACOESCOMPETENCIAS_HISTORICO> AVALIACOESCOMPETENCIAS_HISTORICO { get; set; }
        public virtual DbSet<AVALIACOESCOMPETENCIASNOTAS> AVALIACOESCOMPETENCIASNOTAS { get; set; }
        public virtual DbSet<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES { get; set; }
        public virtual DbSet<AVALIACOESPERFORMANCES_HISTORICO> AVALIACOESPERFORMANCES_HISTORICO { get; set; }
        public virtual DbSet<AVALIACOESPERFORMANCESNOTAS> AVALIACOESPERFORMANCESNOTAS { get; set; }
        public virtual DbSet<CARGOS> CARGOS { get; set; }
        public virtual DbSet<CARGOSNIVEIS> CARGOSNIVEIS { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<COMPETENCIAS> COMPETENCIAS { get; set; }
        public virtual DbSet<DIMENSOES> DIMENSOES { get; set; }
        public virtual DbSet<EIXOS> EIXOS { get; set; }
        public virtual DbSet<EMAILPARAMETROS> EMAILPARAMETROS { get; set; }
        public virtual DbSet<EMPRESAS> EMPRESAS { get; set; }
        public virtual DbSet<PERFIS> PERFIS { get; set; }
        public virtual DbSet<PERFORMANCES> PERFORMANCES { get; set; }
        public virtual DbSet<PERIODOSAVALIACOES> PERIODOSAVALIACOES { get; set; }
        public virtual DbSet<PREMISSAS_RADAR> PREMISSAS_RADAR { get; set; }
        public virtual DbSet<PROJETOS> PROJETOS { get; set; }
        public virtual DbSet<PROJETOSASSOCIADOS> PROJETOSASSOCIADOS { get; set; }
        public virtual DbSet<PROJETOSCOMPLEXIDADES> PROJETOSCOMPLEXIDADES { get; set; }
        public virtual DbSet<PROJETOSSTATUS> PROJETOSSTATUS { get; set; }
        public virtual DbSet<PROJETOSTIPOS> PROJETOSTIPOS { get; set; }
        public virtual DbSet<SUBCOMPETENCIAS> SUBCOMPETENCIAS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<WORKFLOW> WORKFLOW { get; set; }
        public virtual DbSet<RATING> RATING { get; set; }
        public virtual DbSet<EVOLUCAOASSOCIADO> EVOLUCAOASSOCIADO { get; set; }
        public virtual DbSet<EVOLUCAOCOMPETENCIAS> EVOLUCAOCOMPETENCIAS { get; set; }
        public virtual DbSet<EVOLUCAOPERFORMANCE> EVOLUCAOPERFORMANCE { get; set; }
        public virtual DbSet<ASSOCIADOSTEMP> ASSOCIADOSTEMP { get; set; }
        public virtual DbSet<CONSIDERACOESMENTOR> CONSIDERACOESMENTOR { get; set; }
        public virtual DbSet<EQUIPE> EQUIPE { get; set; }
        public virtual DbSet<PROMOCOES> PROMOCOES { get; set; }
        public virtual DbSet<RELACAO_CARGO_SUBCOMPETENCIA> RELACAO_CARGO_SUBCOMPETENCIA { get; set; }
        public virtual DbSet<PRAZOS> PRAZOS { get; set; }
        public virtual DbSet<FATORES> FATORES { get; set; }
        public virtual DbSet<NOTASFATORES> NOTASFATORES { get; set; }
        public virtual DbSet<PALAVRASIRRELEVANTES> PALAVRASIRRELEVANTES { get; set; }
        public virtual DbSet<LIDERESFRENTEINTERNA> LIDERESFRENTEINTERNA { get; set; }
        public virtual DbSet<PARTICIPANTESFRENTEINTERNA> PARTICIPANTESFRENTEINTERNA { get; set; }
        public virtual DbSet<PDI_QUESTOES> PDI_QUESTOES { get; set; }
        public virtual DbSet<PDI_RESPOSTAS> PDI_RESPOSTAS { get; set; }
        public virtual DbSet<COMENTARIOS> COMENTARIOS { get; set; }
        public virtual DbSet<COMPLEXIDADE> COMPLEXIDADE { get; set; }
        public virtual DbSet<FATORESPROJETOS> FATORESPROJETOS { get; set; }
        public virtual DbSet<FRENTEINTERNA> FRENTEINTERNA { get; set; }
        public virtual DbSet<AVALIACOESALOCACOESINTERNAS> AVALIACOESALOCACOESINTERNAS { get; set; }
        public virtual DbSet<NOTASALOCACOESINTERNAS> NOTASALOCACOESINTERNAS { get; set; }
        public virtual DbSet<MODOCALCULOCOMPETENCIAS> MODOCALCULOCOMPETENCIAS { get; set; }
        public virtual DbSet<MENTORADORESPOSTAS> MENTORADORESPOSTAS { get; set; }
        public virtual DbSet<MENTORPERGUNTAS> MENTORPERGUNTAS { get; set; }
        public virtual DbSet<MENTORPERGUNTASMODO> MENTORPERGUNTASMODO { get; set; }
        public virtual DbSet<MENTORPERGUNTASNOTAS> MENTORPERGUNTASNOTAS { get; set; }
        public virtual DbSet<VERTICAL> VERTICAL { get; set; }
        public virtual DbSet<FOTOSASSOCIADOS> FOTOSASSOCIADOS { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<QtdeSubCompetencias_Result> QtdeSubCompetencias(Nullable<int> idCompetencia)
        {
            var idCompetenciaParameter = idCompetencia.HasValue ?
                new ObjectParameter("IdCompetencia", idCompetencia) :
                new ObjectParameter("IdCompetencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QtdeSubCompetencias_Result>("QtdeSubCompetencias", idCompetenciaParameter);
        }
    
        public virtual ObjectResult<PROC_QTDE_SUB_COMPETENCIAS_Result> PROC_QTDE_SUB_COMPETENCIAS(Nullable<int> idCompetencia)
        {
            var idCompetenciaParameter = idCompetencia.HasValue ?
                new ObjectParameter("IdCompetencia", idCompetencia) :
                new ObjectParameter("IdCompetencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_QTDE_SUB_COMPETENCIAS_Result>("PROC_QTDE_SUB_COMPETENCIAS", idCompetenciaParameter);
        }
    }
}
