//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EIXOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EIXOS()
        {
            this.COMPETENCIAS = new HashSet<COMPETENCIAS>();
            this.PREMISSAS_RADAR = new HashSet<PREMISSAS_RADAR>();
            this.EVOLUCAOCOMPETENCIAS = new HashSet<EVOLUCAOCOMPETENCIAS>();
        }
    
        public int IdEixo { get; set; }
        public string Eixo { get; set; }
        public int USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public string TipoAvaliacao { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPETENCIAS> COMPETENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREMISSAS_RADAR> PREMISSAS_RADAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVOLUCAOCOMPETENCIAS> EVOLUCAOCOMPETENCIAS { get; set; }
    }
}
