//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAILPARAMETROS
    {
        public int IdParametro { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string RemetenteEmail { get; set; }
        public string SMTPServer { get; set; }
        public Nullable<int> Porta { get; set; }
        public string Dominio { get; set; }
        public string Password { get; set; }
        public Nullable<bool> UsarSSL { get; set; }
        public string RemetenteNome { get; set; }
        public string ModeloEmailInicio { get; set; }
        public string ModeloEmailDiasSemAlteracao { get; set; }
        public string ModeloEmailDiasParaTermino { get; set; }
        public string ModeloEmailEvolucao { get; set; }
    
        public virtual EMPRESAS EMPRESAS { get; set; }
    }
}
