//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPE
    {
        public int idEquipe { get; set; }
        public int idProjeto { get; set; }
        public int idAssociado { get; set; }
        public Nullable<int> idAssociadoHierarquia { get; set; }
        public Nullable<bool> RespondeAvaliacaoDesempenho { get; set; }
        public Nullable<bool> RespondeAvaliacaoLideranca { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<bool> ATV { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS1 { get; set; }
        public virtual PROJETOS PROJETOS { get; set; }
    }
}
