//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVOLUCAOASSOCIADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVOLUCAOASSOCIADO()
        {
            this.EVOLUCAOCOMPETENCIAS = new HashSet<EVOLUCAOCOMPETENCIAS>();
            this.EVOLUCAOPERFORMANCE = new HashSet<EVOLUCAOPERFORMANCE>();
        }
    
        public int IdEvolucaoAssociado { get; set; }
        public int IdAssociado { get; set; }
        public string Cargo { get; set; }
        public int IdPeriodo { get; set; }
        public Nullable<decimal> NotaCompetencia { get; set; }
        public Nullable<decimal> NotaPerfomance { get; set; }
        public System.DateTime DHC { get; set; }
        public string TipoAvaliacao { get; set; }
        public string Escopo { get; set; }
        public string RatingPerformance { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual PERIODOSAVALIACOES PERIODOSAVALIACOES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVOLUCAOCOMPETENCIAS> EVOLUCAOCOMPETENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVOLUCAOPERFORMANCE> EVOLUCAOPERFORMANCE { get; set; }
    }
}
