//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVOLUCAOCOMPETENCIAS
    {
        public int IdEvoCompetencia { get; set; }
        public int IdEvolucaoAssociado { get; set; }
        public int IdEixo { get; set; }
        public Nullable<decimal> Nota { get; set; }
        public Nullable<decimal> NotaNeutra { get; set; }
    
        public virtual EIXOS EIXOS { get; set; }
        public virtual EVOLUCAOASSOCIADO EVOLUCAOASSOCIADO { get; set; }
    }
}
