//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVOLUCAOPERFORMANCE
    {
        public int IdEvoPerformance { get; set; }
        public int IdEvolucaoAssociado { get; set; }
        public int IdPerformance { get; set; }
        public Nullable<decimal> Nota { get; set; }
    
        public virtual EVOLUCAOASSOCIADO EVOLUCAOASSOCIADO { get; set; }
        public virtual PERFORMANCES PERFORMANCES { get; set; }
    }
}
