//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATORESPROJETOS
    {
        public int idFatorProjeto { get; set; }
        public int idFator { get; set; }
        public int idProjeto { get; set; }
        public Nullable<int> idNotaFator { get; set; }
        public System.DateTime DHC { get; set; }
        public int USR { get; set; }
        public Nullable<bool> ValidGestor { get; set; }
        public Nullable<System.DateTime> DHCValidGestor { get; set; }
        public Nullable<bool> ValidResponsavel { get; set; }
        public Nullable<System.DateTime> DHCValidResponsavel { get; set; }
    
        public virtual FATORES FATORES { get; set; }
        public virtual NOTASFATORES NOTASFATORES { get; set; }
        public virtual PROJETOS PROJETOS { get; set; }
    }
}
