//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FATORES()
        {
            this.FATORESPROJETOS = new HashSet<FATORESPROJETOS>();
        }
    
        public int idFator { get; set; }
        public string Titulo { get; set; }
        public string DescricaoBaixa { get; set; }
        public string DescricaoMedia { get; set; }
        public string DescricaoAlta { get; set; }
        public int Peso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATORESPROJETOS> FATORESPROJETOS { get; set; }
    }
}
