//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOTOSASSOCIADOS
    {
        public int IdFoto { get; set; }
        public int IdAssociado { get; set; }
        public string NomeFoto { get; set; }
        public string AssociadoFoto { get; set; }
        public string Imagem { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
    }
}
