//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRENTEINTERNA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FRENTEINTERNA()
        {
            this.LIDERESFRENTEINTERNA = new HashSet<LIDERESFRENTEINTERNA>();
            this.PARTICIPANTESFRENTEINTERNA = new HashSet<PARTICIPANTESFRENTEINTERNA>();
            this.AVALIACOESALOCACOESINTERNAS = new HashSet<AVALIACOESALOCACOESINTERNAS>();
        }
    
        public int idFrenteInterna { get; set; }
        public string FrenteInterna1 { get; set; }
        public System.DateTime DHC { get; set; }
        public int USR { get; set; }
        public bool ATV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIDERESFRENTEINTERNA> LIDERESFRENTEINTERNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTICIPANTESFRENTEINTERNA> PARTICIPANTESFRENTEINTERNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESALOCACOESINTERNAS> AVALIACOESALOCACOESINTERNAS { get; set; }
    }
}
