//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENTORADORESPOSTAS
    {
        public int idResposta { get; set; }
        public int idPergunta { get; set; }
        public int idMentorado { get; set; }
        public int idMentor { get; set; }
        public int idPeriodo { get; set; }
        public Nullable<int> idNota { get; set; }
        public Nullable<int> Escala { get; set; }
        public string Comentario { get; set; }
        public System.DateTime DHC { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS1 { get; set; }
        public virtual MENTORPERGUNTASNOTAS MENTORPERGUNTASNOTAS { get; set; }
        public virtual MENTORPERGUNTAS MENTORPERGUNTAS { get; set; }
        public virtual PERIODOSAVALIACOES PERIODOSAVALIACOES { get; set; }
    }
}
