//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENTORPERGUNTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENTORPERGUNTAS()
        {
            this.MENTORADORESPOSTAS = new HashSet<MENTORADORESPOSTAS>();
        }
    
        public int idMentorPergunta { get; set; }
        public string Descricao { get; set; }
        public int idModo { get; set; }
        public Nullable<int> ID_CATEGORIA_PERGUNTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENTORADORESPOSTAS> MENTORADORESPOSTAS { get; set; }
        public virtual MENTORPERGUNTASMODO MENTORPERGUNTASMODO { get; set; }
    }
}
