//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPANTESFRENTEINTERNA
    {
        public int idParticipanteFrenteInterna { get; set; }
        public int idAssociado { get; set; }
        public int idFrenteInterna { get; set; }
        public System.DateTime DHC { get; set; }
        public int USR { get; set; }
        public bool ATV { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual FRENTEINTERNA FRENTEINTERNA { get; set; }
    }
}
