//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDI_QUESTOES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PDI_QUESTOES()
        {
            this.PDI_RESPOSTAS = new HashSet<PDI_RESPOSTAS>();
        }
    
        public int idPDIQuestoes { get; set; }
        public string Titulo { get; set; }
        public string Subtitulo { get; set; }
        public string Icone { get; set; }
        public int ColunaPosicao { get; set; }
        public double ColunaTamanho { get; set; }
        public bool BordaEsquerda { get; set; }
        public bool BordaDireita { get; set; }
        public bool BordaCima { get; set; }
        public bool BordaBaixo { get; set; }
        public int ATV { get; set; }
        public System.DateTime DHC { get; set; }
        public int USR { get; set; }
        public Nullable<double> FixTamanho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDI_RESPOSTAS> PDI_RESPOSTAS { get; set; }
    }
}
