//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFORMANCES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERFORMANCES()
        {
            this.EVOLUCAOPERFORMANCE = new HashSet<EVOLUCAOPERFORMANCE>();
        }
    
        public int IdPerformance { get; set; }
        public int IdEmpresa { get; set; }
        public int IdCargo { get; set; }
        public int IdNivel { get; set; }
        public string Performance { get; set; }
        public string PerformanceAbaixo { get; set; }
        public string PerformanceEsperado { get; set; }
        public string PerformanceAcima { get; set; }
        public int USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public string Abrangencia { get; set; }
        public bool InputAutoavaliacao { get; set; }
        public Nullable<int> NotaPadraoAutoAvaliacao { get; set; }
        public bool InputAvaliacaoAsCegas { get; set; }
        public Nullable<int> NotaPadraoAvaliacaoAsCegas { get; set; }
        public bool InputAvaliacaoGestor { get; set; }
        public Nullable<int> NotaPadraoAvaliacaoGestor { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual CARGOS CARGOS { get; set; }
        public virtual CARGOSNIVEIS CARGOSNIVEIS { get; set; }
        public virtual EMPRESAS EMPRESAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVOLUCAOPERFORMANCE> EVOLUCAOPERFORMANCE { get; set; }
    }
}
