//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRAZOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRAZOS()
        {
            this.AVALIACAO = new HashSet<AVALIACAO>();
        }
    
        public int IdPrazo { get; set; }
        public string NomeDisparo { get; set; }
        public int DuracaoAutoAvaliacao { get; set; }
        public int GatilhoAutoAvaliacao { get; set; }
        public int CompensadorAutoAvaliacao { get; set; }
        public int DuracaoAvaliacaoAsCegas { get; set; }
        public int GatilhoAvaliacaoAsCegas { get; set; }
        public int CompensadorAvaliacaoAsCegas { get; set; }
        public int DuracaoAvaliacaoGestor { get; set; }
        public int GatilhoAvaliacaoGestor { get; set; }
        public int CompensadorAvaliacaoGestor { get; set; }
        public int DuracaoFeedback { get; set; }
        public int GatilhoFeedback { get; set; }
        public int CompensadorFeedback { get; set; }
        public int DuracaoMentor { get; set; }
        public int GatilhoMentor { get; set; }
        public int CompensadorMentor { get; set; }
        public System.DateTime DHC { get; set; }
        public int USR { get; set; }
        public int ATV { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACAO> AVALIACAO { get; set; }
    }
}
