//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREMISSAS_RADAR
    {
        public int IdPremissa { get; set; }
        public int IdEmpresa { get; set; }
        public int IdEixo { get; set; }
        public int IdCargo { get; set; }
        public int IdNivel { get; set; }
        public int ValorRadarPeers { get; set; }
        public int ValorBaseAutoAvaliacao { get; set; }
        public int ValorBaseAvaliacaoGestor { get; set; }
        public int USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
    
        public virtual CARGOS CARGOS { get; set; }
        public virtual CARGOSNIVEIS CARGOSNIVEIS { get; set; }
        public virtual EIXOS EIXOS { get; set; }
    }
}
