//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJETOSASSOCIADOS
    {
        public int IdProjetoAssociado { get; set; }
        public int IdProjeto { get; set; }
        public int IdAssociado { get; set; }
        public Nullable<int> IdGestor { get; set; }
        public System.DateTime DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public string Comentario { get; set; }
        public int USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public Nullable<int> IdAvaliador { get; set; }
        public string TipoAvaliacao { get; set; }
        public string Escopo { get; set; }
        public Nullable<int> IdPeriodoSinalizado { get; set; }
        public Nullable<bool> flagNovaAlocacao { get; set; }
        public Nullable<bool> flagExcluirAlocacao { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS1 { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS2 { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS3 { get; set; }
        public virtual PROJETOS PROJETOS { get; set; }
    }
}
