//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJETOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJETOS()
        {
            this.AVALIACAO = new HashSet<AVALIACAO>();
            this.AVALIACOESCOMPETENCIAS = new HashSet<AVALIACOESCOMPETENCIAS>();
            this.AVALIACOESPERFORMANCES = new HashSet<AVALIACOESPERFORMANCES>();
            this.PROJETOSASSOCIADOS = new HashSet<PROJETOSASSOCIADOS>();
            this.EQUIPE = new HashSet<EQUIPE>();
            this.FATORESPROJETOS = new HashSet<FATORESPROJETOS>();
        }
    
        public int IdProjeto { get; set; }
        public int IdEmpresa { get; set; }
        public int IdCliente { get; set; }
        public int IdAssociadoResponsavel { get; set; }
        public int IdAssociadoGestor { get; set; }
        public int IdStatus { get; set; }
        public int IdTipo { get; set; }
        public int IdComplexidade { get; set; }
        public string Projeto { get; set; }
        public System.DateTime DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public int USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public string Codigo { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS1 { get; set; }
        public virtual ASSOCIADOS ASSOCIADOS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACAO> AVALIACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESCOMPETENCIAS> AVALIACOESCOMPETENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVALIACOESPERFORMANCES> AVALIACOESPERFORMANCES { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual EMPRESAS EMPRESAS { get; set; }
        public virtual PROJETOSCOMPLEXIDADES PROJETOSCOMPLEXIDADES { get; set; }
        public virtual PROJETOSSTATUS PROJETOSSTATUS { get; set; }
        public virtual PROJETOSTIPOS PROJETOSTIPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJETOSASSOCIADOS> PROJETOSASSOCIADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPE> EQUIPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATORESPROJETOS> FATORESPROJETOS { get; set; }
    }
}
