//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJETOSCOMPLEXIDADES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJETOSCOMPLEXIDADES()
        {
            this.PROJETOS = new HashSet<PROJETOS>();
            this.RATING = new HashSet<RATING>();
        }
    
        public int IdComplexidade { get; set; }
        public string Codigo { get; set; }
        public string Complexidade { get; set; }
        public Nullable<decimal> Ponderacao { get; set; }
        public string USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public Nullable<decimal> FaixaInicial { get; set; }
        public Nullable<decimal> FaixaFinal { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> PesoPonderado { get; set; }
        public Nullable<decimal> SomaMinimaFator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJETOS> PROJETOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATING> RATING { get; set; }
    }
}
