//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOCOES
    {
        public int idPromocao { get; set; }
        public Nullable<int> idAssociado { get; set; }
        public Nullable<int> idCargoAnterior { get; set; }
        public Nullable<int> idCargoNovo { get; set; }
        public Nullable<System.DateTime> DataPromocao { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<bool> ATV { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual CARGOS CARGOS { get; set; }
        public virtual CARGOS CARGOS1 { get; set; }
    }
}
