//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATING
    {
        public int IdRating { get; set; }
        public int IdComplexidade { get; set; }
        public string Performance { get; set; }
        public decimal FaixaInicial { get; set; }
        public decimal FaixaFinal { get; set; }
        public int ATV { get; set; }
        public System.DateTime DHC { get; set; }
    
        public virtual PROJETOSCOMPLEXIDADES PROJETOSCOMPLEXIDADES { get; set; }
    }
}
