//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELACAO_CARGO_SUBCOMPETENCIA
    {
        public int idRelacao { get; set; }
        public int idCargo { get; set; }
        public int idSubcompetencia { get; set; }
        public string Descricao { get; set; }
    
        public virtual CARGOS CARGOS { get; set; }
        public virtual SUBCOMPETENCIAS SUBCOMPETENCIAS { get; set; }
    }
}
