//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBCOMPETENCIAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBCOMPETENCIAS()
        {
            this.COMPETENCIAS = new HashSet<COMPETENCIAS>();
            this.RELACAO_CARGO_SUBCOMPETENCIA = new HashSet<RELACAO_CARGO_SUBCOMPETENCIA>();
        }
    
        public int IdSubCompetencia { get; set; }
        public string SubCompetencia { get; set; }
        public Nullable<int> USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
        public string TipoAvaliacao { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPETENCIAS> COMPETENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELACAO_CARGO_SUBCOMPETENCIA> RELACAO_CARGO_SUBCOMPETENCIA { get; set; }
    }
}
