//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW
    {
        public int IdWorkflow { get; set; }
        public int IdEmpresa { get; set; }
        public int IdPeriodo { get; set; }
        public System.DateTime DataInicio { get; set; }
        public int DiasAutoAvaliacao { get; set; }
        public int DiasAvaliacaoCegas { get; set; }
        public int DiasAvaliacaoGestor { get; set; }
        public int DiasFeedback { get; set; }
        public int DiasAlertaSemAlteracao { get; set; }
        public int USR { get; set; }
        public Nullable<System.DateTime> DHC { get; set; }
        public Nullable<int> ATV { get; set; }
    
        public virtual ASSOCIADOS ASSOCIADOS { get; set; }
        public virtual EMPRESAS EMPRESAS { get; set; }
        public virtual PERIODOSAVALIACOES PERIODOSAVALIACOES { get; set; }
    }
}
